#
# REG_USERNAME="admin"
# REG_PASWORD="snowdrop"
# REG_SERVER="registry.local:5000"
# kubectl create ns buildpack
# kubectl create secret docker-registry local-registry -n buildpack --docker-server=$REG_SERVER --docker-username=$REG_USERNAME --docker-password=$REG_PASWORD
---
apiVersion: v1
kind: Namespace
metadata:
  name: buildpack
---
apiVersion: v1
kind: Secret
metadata:
  name: local-registry
  namespace: buildpack
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5sb2NhbDo1MDAwIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InNub3dkcm9wIiwiYXV0aCI6IllXUnRhVzQ2YzI1dmQyUnliM0E9In19fQ==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildpack
  namespace: buildpack
secrets:
  - name: local-registry
imagePullSecrets:
  - name: local-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
  namespace: buildpack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500m
---
apiVersion: v1
kind: Pod
metadata:
  name: buildah-poc
  namespace: buildpack
spec:
  volumes:
    - name: cache
      hostPath:
        path: /cache
    - name: workspace
      hostPath:
        path: /workspace
  initContainers:
    - name: buildah-bud
      image: localhost:5000/buildah-app
      env:
      - name: LOGGING_FORMAT
        value: "color"
      - name: LOGGING_LEVEL
        value: "debug"
      - name: WORKSPACE_DIR
        value: "/workspace"
      - name: DOCKERFILE_NAME
        value: Dockerfile-1
      - name: EXTRACT_LAYERS
        value: "true"
      - name:  FILES_TO_SEARCH
        value: "good.txt"
      workingDir: /workspace
      command: [ "/buildah-app" ]
      volumeMounts:
      - name: cache
        mountPath: /cache
      - name: workspace
        mountPath: /workspace
      imagePullPolicy: Always
      securityContext:
        privileged: true
    # - name: check-after
    #   image: registry.access.redhat.com/ubi8:8.4-211 # busybox:1.28
    #   env:
    #     - name: LAYERS_DIR
    #       value: "/layers"
    #   command: [ "/bin/sh","-c" ]
    #   args:
    #     - |
    #       echo "## Check if Node exists and version"
    #       echo "## Append $LAYERS_DIR/usr/bin to the path"
    #       export PATH="$LAYERS_DIR/usr/bin:$PATH"
    #       echo $PATH
    #       type -a node
    #       node -v
    #   volumeMounts:
    #     - name: layers
    #       mountPath: /layers
    #   securityContext:
    #     privileged: true
  containers:
    - name: completion
      image: busybox:1.28
      command: [ "/bin/sh","-c","--" ]
      args: [ "while true; do sleep 30; done;" ]
  serviceAccountName: buildpack

