#
# REG_USERNAME="admin"
# REG_PASWORD="snowdrop"
# REG_SERVER="registry.local:5000"
# kubectl create secret docker-registry local-registry -n fs --docker-server=$REG_SERVER --docker-username=$REG_USERNAME --docker-password=$REG_PASWORD
---
apiVersion: v1
kind: Namespace
metadata:
  name: buildpack
---
apiVersion: v1
kind: Secret
metadata:
  name: local-registry
  namespace: buildpack
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5sb2NhbDo1MDAwIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InNub3dkcm9wIiwiYXV0aCI6IllXUnRhVzQ2YzI1dmQyUnliM0E9In19fQ==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildpack
  namespace: buildpack
secrets:
  - name: local-registry
imagePullSecrets:
  - name: local-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-poc-cache
  namespace: buildpack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildah-poc
  namespace: buildpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildah-poc
  template:
    metadata:
      labels:
        app: buildah-poc
    spec:
      volumes:
        - name: cache-dir
          persistentVolumeClaim:
            claimName: buildah-poc-cache
        - name: host
          hostPath:
            path: /
      initContainers:
        - name: buildah-bud
          image: registry.local:5000/snowdrop/buildah-poc
          env:
            - name: WORKSPACE_DIR
              value: "/workspace"
            - name: STORAGE_DRIVER
              value: "vfs"
          workingDir: /workspace
          command: [ "/bin/sh","-c" ]
          args:
            - |
              set -e
              echo -e "\n## Execute buildah bud"
              cp /Dockerfile $WORKSPACE_DIR/
              cp /undocker.py $WORKSPACE_DIR/
              /bud

              echo -e "## Check if the image has been created locally"
              GRAPH_DRIVER="vfs"
              STORAGE_DIR=/var/lib/containers/storage
              buildah --storage-driver $GRAPH_DRIVER images

              EXTRACT_DIR="/host"
              alias docker=podman
              REPO="localhost/buildpack-buildah"
              echo "#### Extract the layer to $EXTRACT_DIR ####"

              TAG=$(buildah --storage-driver $GRAPH_DRIVER images | awk -v r="$REPO" '$0 ~ r {print $2;}')
              LAST_LAYER_ID=$(docker save $REPO:$TAG | ./undocker.py --layers | tail -n1)
              echo "Layer ID: $LAST_LAYER_ID"
              docker save $REPO:$TAG | ./undocker.py -iv -o $EXTRACT_DIR -l $LAST_LAYER_ID

              echo "#### Node version"
              $EXTRACT_DIR/usr/bin/node -v
          volumeMounts:
            - name: cache-dir
              mountPath: /workspace
            - name: host
              mountPath: /host
          imagePullPolicy: Always
          securityContext:
            privileged: true
      containers:
        - name: completion
          image: busybox:1.28
          command: [ "/bin/sh","-c" ]
          args:
            - |
              echo "# Builah bud executed successfully"
      serviceAccountName: buildpack

