# kind create cluster --config ./k8s/cfg.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: $(pwd)/kaniko/workspace
      containerPath: /workspace
    - hostPath: $(pwd)/kaniko/cache
      containerPath: /cache