---
apiVersion: v1
kind: Namespace
metadata:
  name: kaniko
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  volumes:
    - name: cache-dir
      hostPath:
        path: /cache
    - name: wks-dir
      hostPath:
        path: /workspace
  initContainers:
  - name: build
    image:  localhost:5000/kaniko-app
    command: [ "/kaniko-app" ]
    env:
      - name: "EXTRACT_LAYERS"
        value: "true"
      - name: "IGNORE_PATHS"
        value: "/var/run"
      - name: "FILES_TO_SEARCH"
        value: "good.txt"
      - name: "LOGGING_LEVEL"
        value: "info"
      - name: "LOGGING_FORMAT"
        value: "color"
      - name: "DOCKER_FILE_NAME"
        value: "ubi8-good-bye"
    imagePullPolicy: Always
    volumeMounts:
    - name: wks-dir
      mountPath: /workspace
    - name: cache-dir
      mountPath: /cache
  containers:
  - name: completion
    image: alpine:3
    command: [ "/bin/sh","-c" ]
    args:
      - |
        echo "## Build completed successfully"
