---
apiVersion: v1
kind: Namespace
metadata:
  name: kaniko
---
apiVersion: v1
kind: Secret
metadata:
  name: local-registry
  namespace: kaniko
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5sb2NhbDo1MDAwIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InNub3dkcm9wIiwiYXV0aCI6IllXUnRhVzQ2YzI1dmQyUnliM0E9In19fQ==
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko
  namespace: kaniko
secrets:
  - name: local-registry
imagePullSecrets:
  - name: local-registry
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  volumes:
    - name: cache-dir
      hostPath:
        path: /cache
    - name: wks-dir
      hostPath:
        path: /workspace
  initContainers:
  - name: build
    image:  registry.local:5000/kaniko-project/executor:alpine #gcr.io/kaniko-project/executor:1.0
    #args:
    #- '--dockerfile=/workspace/Dockerfile'
    #- '--context=/workspace/'
    #- '--verbosity=info'
    #- '--no-push'
    command: [ "/bin/sh","-c" ]
    args:
      - |
        set -e
        echo -e "Launch kaniko executor ..."
        /kaniko/executor --dockerfile=/workspace/Dockerfile --context=/workspace/ --verbosity=info --no-push
        echo "Check if file created exists ..."
        ls -la /
        ls -la /kaniko
        ls -la /workspace
    imagePullPolicy: Always
    volumeMounts:
    - name: wks-dir
      mountPath: /workspace
    - name: cache-dir
      mountPath: /cache
  - name: check-content
    image: alpine:3.14
    command: [ "/bin/sh","-c" ]
    args:
      - |
        set -e
        echo -e "Check about hello.txt file ..."
        ls -la /
        ls -la /workspace
        ls -la /cache
    volumeMounts:
    - name: cache-dir
      mountPath: /cache
    - name: wks-dir
      mountPath: /workspace
  containers:
  - name: completion
    image: alpine:3.14
    command: [ "/bin/sh","-c" ]
    args:
      - |
        echo "## Build completed successfully"
  serviceAccountName: kaniko