---
apiVersion: v1
kind: Namespace
metadata:
  name: kaniko
---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  volumes:
    - name: cache-dir
      hostPath:
        path: /cache
    - name: wks-dir
      hostPath:
        path: /workspace
  initContainers:
  - name: build
    image:  localhost:5000/kaniko-app
    command: [ "/kaniko-app" ]
    env:
      - name: "LOGGING_LEVEL"
        value: "info"
      - name: "LOGGING_FORMAT"
        value: "color"
      - name: "DOCKER_FILE_NAME"
        value: "Dockerfile"
    imagePullPolicy: Always
    volumeMounts:
    - name: wks-dir
      mountPath: /workspace
    - name: cache-dir
      mountPath: /cache
  - name: check-content
    image: alpine:3
    command: [ "/bin/sh","-c" ]
    args:
      - |
        set -e
        echo -e "Check about hello.txt file ..."
        ls -la /
        ls -la /workspace
        ls -la /cache
    volumeMounts:
    - name: cache-dir
      mountPath: /cache
    - name: wks-dir
      mountPath: /workspace
  containers:
  - name: completion
    image: alpine:3
    command: [ "/bin/sh","-c" ]
    args:
      - |
        echo "## Build completed successfully"