on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:
  buildah_e2e_test:
    runs-on: ubuntu-latest
    env:
      KIND_CL_NAME: e2e-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Buildah Poc
        working-directory: buildah
        run: ./hack/build.sh

      - name: clean resident local docker
        if: ${{ env.ACT }}
        continue-on-error: true
        run: |
          for DIMG in "$KIND_CL_NAME-control-plane "; do
            docker stop $DIMG ; docker rm $DIMG ;
          done ;
          sleep 1

      - name: Create Kubernetes Kind Cluster
        uses: container-tools/kind-action@v1.7.0
        with:
          cluster_name: e2e-test
          registry: true

      - name: Tag and push the image
        run: |
          REGISTRY="localhost:5000"
          docker tag buildah-app $REGISTRY/buildah-app
          docker push $REGISTRY/buildah-app

      - name: Deploy the buildah pod to perform a Dockerfile build
        working-directory: buildah
        run: kubectl apply -f ./k8s/manifest-cloud.yml

      - name: Wait till pod's status is running
        working-directory: buildah
        run: ./hack/check_job_status.sh

      - name: Delete cluster
        run: kind delete cluster

